### PR TITLE
attempt to subtract a model of the bright flux

### PR DESCRIPTION
**Pull request by keflavich**

### CODE REVIEW

**Comment by keflavich** [comment]
Doesn't work well at all; the residual noise is really high:

image

the blue panel is subtracting for _just this field_, the other panel with the deep negatives is from including the surrounding fields.  Why is it so badly oversubtracted?

**Comment by baobabyoo** [comment]
Hmm, I had this account but haven't learned much about how to use it. 
I guess the bad over-subtraction is due to missed to correct the primary beam. A step-by-step procedure would be:
1. build the clean model from the central field
2. Use "immath" to make a primary beam correction for the clean model, and then use "immath" again to multiply the image by the primary beam of the adjacent fields.
3. Use ft to model the visibility response from the adjacent fields.

**Comment by baobabyoo** [comment]
The second step should be equivalent to the Miriad task "demos". You can check your paper to be submitted, which has a very detailed description about what we tried:
https://www.overleaf.com/read/mgykyktdgcjd
Section 3.1 has the description about the self-calibration, although was in Miriad.

**Comment by keflavich** [comment]
@baobabyoo shouldn't ft account for the primary beam?  Hmmm... maybe it takes parameters like 'mosaic'....

**Comment by keflavich** [comment]
multiscale cleaning has resulted in a large improvement, though I had to select a threshold fairly carefully (multiscale succeeded with threshold=30 mJy, will try with 20 mJy next)

**Comment by keflavich** [comment]
This is pretty disturbing: the multi-field clean results in a significantly lower peak flux.  

```
Stats (mfs):
dirty:    peak=0.96772 sigma=0.02894 s/n=33.44437
clean:    peak=0.63233 sigma=0.00562 s/n=112.58168
selfcal:  peak=0.64452 sigma=0.00495 s/n=130.14038
selfcal2: peak=0.64149 sigma=0.00487 s/n=131.59457
multifield peak=0.32737 sigma=0.00487 s/n=67.21690
multifield_selfcal peak=0.33390 sigma=0.00485 s/n=68.77951
```

**Comment by keflavich** [comment]
Is the primary beam accounted for at all when cleaning?  I certainly hope so, but evidence suggests not...

**Comment by keflavich** [comment]
50% reduction in flux including neighbors.

```
Stats (mfs):
dirty:             peak=0.96772 sigma=0.02894 s/n=33.44437
clean:             peak=0.60787 sigma=0.00709 s/n=85.79666
selfcal:           peak=0.62723 sigma=0.00563 s/n=111.42869
selfcal2:          peak=0.63354 sigma=0.00522 s/n=121.26594
selfcal3:          peak=0.62423 sigma=0.00532 s/n=117.23818
selfcal4 ampphase: peak=0.63166 sigma=0.00433 s/n=145.88588
multifield:        peak=0.33414 sigma=0.00420 s/n=79.62421
multifield_selfcal peak=0.33947 sigma=0.00410 s/n=82.82777
```

image

**Comment by baobabyoo** [comment]
multifield = multiscale?? 
I prefer MEM over multiscale clean. Mathematically it is more natural. The JVLA+GBT NH3 image cubes I generated for Betsy was MEM cleaned. It works very reasonably to me.

**Comment by keflavich** [comment]
No, multifield = includes adjacent pointings, i.e. mosaiced.

MEM in CASA has not worked on this field, it always diverges.

**Comment by baobabyoo** [comment]
Hmm, I haven't tried MEM in CASA. The Miriad MEM works OK. The major complain about MEM is just the spatially varying angular resolution, and the poor convergence towards the point sources. If you're using multi-scale clean, you will also have a spatially varying angular resolution. And you probably don' t really have point sources. The algorithm should fundamentally work, if it was programmed properly. 

Not sure how CASA mosaic imaging take care of the primary beam. The decreased peak flux sounds strange. If you image those mosaic fields independently and then make primary beam correction for the cleaned image, do you get the consistent peak flux level?

**Comment by baobabyoo** [comment]
It looks like there are quite some real structures immersed in the negative brightness bow. I think combining 7m but give it a low weighting, will also help your self-calibration. 

It doesn't seems like you're subject to a huge phase de-coherence. It may be OK to leave the adjacent fields not self-calibrated. You can try self-calibrating them, and not self-calibrating them. There are also things to try, e.g. (1) constructing the bright source model with only the central field, (2) constructing the bright source model with only a adjacent field (and then use it to self-calibrate itself), and (3) constructing the bright source model based on the mosaic image.

**Comment by keflavich** [comment]
1. MEM vs multiscale - I disagree that multiscale results in different resolution: the resolution really does not change, just how the image is cleaned.  Maybe the same is true of MEM and I am just being pedantic, I'm not sure.  I don't have much experience tweaking MEM, so maybe I'll try it further now.
2. Imaging the adjacent fields with non-mosaic mode is a good idea.  Tedious, but a good idea.
3. I have tried with 7m included, but it so far has just created major divergences in CLEAN.
4. I agree that there doesn't seem to be too much phase decoherence, only enough to result in maybe a 50% improvement.  However, there probably is dramatic amplitude error - not REAL amplitude error, but amplitude error caused either by un-masked lines or by uncorrected primary beam attenuation.  I'm not sure if self-cal can correct this, but in principle I would think it could?

**Comment by keflavich** [comment]
self-cal with 7m included results in essentially all solutions being flagged in the 7m data.  Not terribly surprising, but not good.  Though... I think this is because of an incorrect concat earlier... I have to double check this.

**Comment by keflavich** [comment]
the `.model` files have units of `Jy/Pixel` and therefore are not easily interpreted.  However, if I scale Jy/Pixel to Jy/beam, the model is ~10x brighter than the image.  So there is no consistency.

**Comment by baobabyoo** [comment]
The .model file is a collection of a lot of delta function. The final image is generated by convolving .model with a Gaussian beam.

**Comment by keflavich** [comment]
yes, I know - but the values in the model are not consistent with scaling to a gaussian beam, at least not in the way I would expect.  However, conversion between Jy/pixel and Jy/beam is always tricky; it may be that they convolve with a volume-normalize Gaussian beam and then scale by PPBEAM... though in principle, that should be equivalent to multiplying by 1....

**Comment by keflavich** [comment]
The model is not PB-corrected:

image

**Comment by keflavich** [comment]
this is more like it:

```
Stats (mfs):
dirty:             peak=1.15773 sigma=0.04750 s/n=24.37164
clean:             peak=0.84051 sigma=0.01998 s/n=42.06885
selfcal:           peak=0.87721 sigma=0.01524 s/n=57.54835
selfcal2:          peak=0.90063 sigma=0.01379 s/n=65.31930
selfcal3:          peak=0.89117 sigma=0.01433 s/n=62.19206
selfcal4 ampphase: peak=0.89345 sigma=0.01407 s/n=63.51378
multifield:        peak=0.45886 sigma=0.00497 s/n=92.34640
multifield_selfcal peak=0.45914 sigma=0.00486 s/n=94.41704
```

that's what happens when I pbcor.    The dynamic range is still much lower than I want, but at least including more data = lower noise.  I'm still very scared, though, because the signal is also much lower!

**Comment by keflavich** [comment]
I filed NRAO CASA ticket #7712 about this

**Comment by baobabyoo** [comment]
Glad that I have been staying with Miriad.  :P

**Comment by keflavich** [comment]
I was wrong, the factors between different fields are smaller after PBCOR, more like 15-20%.  However, they affect the mosaic clean much more strongly than the CSCLEAN.  The problem actually appears to be a phase problem: the point sources are not aligned.  This clearly explains why there _is_ a factor of ~2 error in the mosaic!

**Comment by baobabyoo** [comment]
If this is the case, maybe build the model with just the central field, and then self-calibrate base on this model the rest of the fields, will make the best coherence, hopefully.

**Comment by keflavich** [comment]
Yes, that's my next step.

**Comment by keflavich** [comment]
Do you recall, if I do multiple iterations of gaincal without doing applycal, do I want to use only the _last_ iteration, or all of them?  I think I want to just use the last....

**Comment by baobabyoo** [comment]
Yes it should be the last one.

**Comment by keflavich** [comment]
I'm going to try amp+phase, which might be stupid.  Unfortunately, it looks like the S/N is too low in some pointings on some baselines, even though this is a 0.3 Jy source...

**Comment by keflavich** [comment]
I gave up on amp self-cal.  After phase self-cal, the pointing looks a bit better but still not perfect, however, now there IS a 2x discrepancy for 2 of the pointings.  The rest are OK.  The two with big discrepancies are both field-edge pointings, and it looks like they suffer from the 'wrap' problem.

**Comment by baobabyoo** [comment]
What we did for the Galactic center is to just subtract the bright source model off, and hopefully the residual doesn't impact that much to the dynamic range when you merge the adjacent mosaic fields. It didn't, for our case. But we use Miriad. We didn't try to subtract the bright source model with CASA.

**Comment by baobabyoo** [comment]
You phase error is curious. 
Our Galactic center mosaic is subject to a strange phase jump issue (https://www.overleaf.com/read/mgykyktdgcjd). While the gain calibration data look perfectly fine, the phase of the Sgr A\* indicated that we were subject to +-50 deg phase jumps when switching over mosaic fields. We had reported this problem. Our project will be executed again in cycle-3, with a modified mosaic strategy to investigate this phase jump (approved with a major change request).

**Comment by keflavich** [comment]
which figure/section should I look at for that?

**Comment by baobabyoo** [comment]
No figure, but the beginning of Section 3.

**Comment by keflavich** [comment]
Any thoughts on what would be good to plot?   I guess I could go one antenna at a time, but phase vs time over a selected UV range is not super helpful:
image

**Comment by keflavich** [comment]
Hmm, maybe I am seeing those same phase jumps.  Same plot, for single baselines:
image

image

image

though admittedly, I don't have a true point source, so some phase jumps may be real

**Comment by baobabyoo** [comment]
sgra phase 2 baseline
The attached plot is made with the inner 13 mosaic fields, which can detect the Sgr A\* (S/N is somewhat poor with the outer most 6 fields). I used the task "fixvis" to shift their phase referencing center to the location of the Sgr A*, and then plot the phase vs. time per baseline. We were only able to self-calibrate the innermost 7 fields, of which the gain phase self-calibration solution consistently indicate the +-50 deg phase jumps. 

This is what we attach when requesting to JAO. It might not be easy to understand the phase if you're field is not dominated by a point-like source.

**Comment by keflavich** [comment]
how did you set up the multipanel approach there?  I did fixvis, and made the extra panels with "Options", but now I don't know how to populate them

**Comment by baobabyoo** [comment]
screenshot from 2015-12-10 08 35 28
In Option page, change row and column.

**Comment by keflavich** [comment]
Yes, but then how do you set the `iteraxis` (or whatever is needed to populate those panels)

**Comment by keflavich** [comment]
Specifying on the command line seems to have worked

**Comment by baobabyoo** [comment]
Yes I iterate over baseline, while only picking the longest baselines to ensure I was looking at the point like source.

**Comment by keflavich** [comment]
Like this:
image

But how do you specify `iteraxis` from within `plotms`?  Is it possible, or do you need to set it when you call `plotms` from the command line?

**Comment by baobabyoo** [comment]
In our 1st iteration phase self-calibration solution, we also consistently obtained the ~+- 50 deg corrections (antenna based). And after correcting the phase term, the image quality was indeed very significantly improved. So we were pretty sure those are systematic phase offsets with a unknown cause. The observations of the gaincal looks smooth over a relatively large time interval, after applying wvr.

**Comment by keflavich** [comment]
my phase jumps are pretty bad:
image

but unfortunately phase self-cal yielded an extremely minor improvement:

```
Stats (mfs):
dirty:             peak=1.15773 sigma=0.04750 s/n=24.37164
clean:             peak=0.84051 sigma=0.01998 s/n=42.06885
selfcal:           peak=0.87721 sigma=0.01524 s/n=57.54835
selfcal2:          peak=0.90063 sigma=0.01379 s/n=65.31930
selfcal3:          peak=0.89117 sigma=0.01433 s/n=62.19206
selfcal4 ampphase: peak=0.89345 sigma=0.01407 s/n=63.51378
multifield:        peak=0.45886 sigma=0.00497 s/n=92.34640
multifield_selfcal peak=0.45914 sigma=0.00486 s/n=94.41703
```

**Comment by baobabyoo** [comment]
screenshot from 2015-12-10 08 43 46
Like this.  :-)

**Comment by keflavich** [comment]
Ach, there it is!   I was clicking back and forth through tabs for 5 minutes and couldn't find that microscopic word.

Anyway, here's the fixvis + plotting code:
https://github.com/keflavich/W51_ALMA_2013.1.00308.S/blob/98636482d9105b6a988ec1db8c798d53119ebcda/script_12m/fixvis_phasetest.py
(this is _before_ phase self-cal)

**Comment by baobabyoo** [comment]
Probably try make a image out of 1/3 of your data but in the long baseline range, and see what could be expected with a degraded sensitivity, but without the confusion of the extended stuff?

**Comment by keflavich** [comment]
here it is after selfcal:
image

Yes, perhaps imaging only the long baselines would work... as is, I'm only plotting relatively long baselines

**Comment by keflavich** [comment]
@baobabyoo when you're using a subset of the data, how do you compute the theoretical noise limit?  Do you just use the ALMA sensitivity calculator, or try to calculate it directly from the data?

**Comment by baobabyoo** [comment]
When you're using only 30% of your data, then the theoretical noise limit per beam is (1 / sqrt(30%) ) of the original value.

**Comment by keflavich** [comment]
Yes, exactly - what do you take as "original value"? The theoretical one from the sensitivity calculator?

**Comment by baobabyoo** [comment]
There are a few ways: (1) after uvcontsub, measure the rms noise from one line free channel image and then scale it to the channel width you will be using, or (2) somehow properly jacknife your continuum data (use the dirty image generated from the first half of every scan, subtract that from the dirty image generated from the last half of every scan.), etc. This should nearly subject all signal and leave you with noise. Sensitivity calculator doesn't consider the actual weather condition you got. It is better to just measure it.

**Comment by keflavich** [comment]
Fair enough, that's reasonable.  Do you often make images at different resolution?  I am planning on imaging with both uniform, robust 0.5, and natural weighting (because I expect each image to show different things), so I'll have to measure the noise in each independently.

**Comment by baobabyoo** [comment]
Yes I always publish images with different resolution.  :-)  
I even publish dirty image. Our way of doing thing should be optimized for our purposes.

**Comment by keflavich** [comment]
I have considered publishing dirty images - I think it makes sense, EXCEPT the flux scale is necessarily wrong because the dirty beam may incorporate flux from far away.  For most continuum images, that's not a problem, but for line images (HI, CO) it is.

(notes for me) the thermal noise in a _flagged_ 1.875 GHz SPW is ~0.37 mJy/beam with robust 0.  It turns out I never made the unflagged equivalent... todo!

**Comment by keflavich** [comment]
OK, looks like selfcal did work, in that it allowed me to clean much deeper without reaching instabilities:

image

**Comment by keflavich** [comment]
With the deeper clean:

```
Stats (mfs):
dirty:             peak=1.41432 sigma=0.05202 s/n=27.18663
clean:             peak=0.95247 sigma=0.02290 s/n=41.58836
selfcal:           peak=0.96808 sigma=0.02296 s/n=42.15978
selfcal2:          peak=0.97516 sigma=0.02336 s/n=41.74172
selfcal3:          peak=0.97544 sigma=0.02400 s/n=40.64456
selfcal4 ampphase: peak=1.00502 sigma=0.02160 s/n=46.52766
multifield:        peak=0.58759 sigma=0.00516 s/n=113.98016
multifield_selfcal peak=0.61455 sigma=0.00378 s/n=162.40208
multifield_selfcal peak=0.61852 sigma=0.00169 s/n=366.74661
```

getting to 360!  Still not all the way there... I'm a little hesitant to clean much deeper but I'll try...

**Comment by baobabyoo** [comment]
Congratulations!

If you make mosaic imaging, it might be necessary to use a clean box (a polygon region is OK). Somehow CASA mosaic clean is very easily trapped to some defect features at the edge of the mosaic field of view.

**Comment by keflavich** [comment]
Is this overcleaned or trustworthy?  I suspect overcleaned, but if it's real, it's also real exciting.

```
multifield_selfcal peak=0.61761 sigma=0.00074 s/n=838.95453
```

image

**Comment by baobabyoo** [comment]
Overcleaned I think. Those lots of compact sources may not be real. I think clean doesn't converge well for the faint extended component. You might switch to multi-scale clean after some itegrations, or switch to MEM, to recover the extended component more reasonably.

**Comment by baobabyoo** [comment]
Most of the real structures should have their molecular line counterparts.

**Comment by keflavich** [comment]
I'm already using multiscale.  I haven't tried MEM again yet.  I don't trust the point sources, but they are sort of what I'm looking for... I'm not really sure how to test their trustworthiness.  Maybe I can do the model subtraction at a shallower clean, then deep clean later.  With a higher minpb.

Real structures will _not_ necessarily have molecular counterparts for a wide variety of reasons, the biggest being confusion from the local cloud.  

I've tried running self-cal on the full image, and it "worked" to some degree, but when I tried using an amp+phase calibration, it started flagging out data, even though I explicitly told it not to:

```
applycal(vis=vis3, field="", gaintable=["phase_4.cal", 'ampphase.cal'],
         interp="linear", applymode='calonly')
```

my understanding is `'calonly'` is supposed to not flag the data.

**Comment by keflavich** [comment]
actually, a good test would be to do the same cleaning on a different SPW.  If the sources move, then they're obviously not real.

**Comment by baobabyoo** [comment]
If those faint point sources are not real, merely changing the robust parameter will make them move. To improve the phase self-calibration, you may consider to do all four spws together, using the option combine='spw'. This will give you a bit more S/N to go done to the shorter solution interval. 
Self-calibration solution should only be derived from fields which have strong S/N. You may interpolate the solution to the other field in applycal.

**Comment by keflavich** [comment]
I'm already using the shortest solution interval, which is fine for the bright sources where selfcal appears necessary.  I'm using a threshold of S/N > 5 in the full image to ensure that no spurious solutions get in.  I believe this should _automatically_ select fields with strong signal, as for others all solutions will be flagged out.

True, changing robust should move them - I'll give that a shot too.

**Comment by keflavich** [comment]
the structures are consistent with robustness parameter change from -2.0 to 0.0

image

**Comment by baobabyoo** [comment]
Hmm.... Interesting.... 
But it seems they also have the low brightness brothers?

**Comment by keflavich** [comment]
Yes, there are many of these.  I still don't trust them, so I'm going to image the other SPWs now (I've spent the last half hour working on that.... have to identify a pseudocontinuum for splitting, then flag & split, etc.)

**Comment by keflavich** [comment]
Unfortunately, it looks like `appylcal` with `applymode='calonly'` works for _phase_ but not for _amplitude_ calibration.  All my real data is getting flagged out in my full-field selfcal attempt.  It is perplexing.

**Comment by keflavich** [comment]
When I try to selfcal on the full image, I get the following problems:
1. If I use amplitude self-cal, all of the regions that have signal disappear in cleaning.  According to `flagdata(mode='summary')`, the number of flags did not change, therefore flagging is not the answer.
2. The extended structure toward the center of the image goes away with iterations of phase self-cal.  If I've tuned this correctly, as I think I have, these regions should be excluded from the self-calibration because they lack emission, and therefore they should not change.  So, why are they changing?

image

These are done with uniform weighting.  The top-center is no self-cal, top left is dirty, bottom-center is 1 iteration, middle-center is 3 iterations with a deep clean, middle-right is 4 iterations including 1 of amplitude + phase.

**Comment by baobabyoo** [comment]
I always avoid including the fields without strong compact sources, when deriving the self-calibration solutions. You might inspect the phase solution you obtained and see what happen. It might be possible that you get bad phase solution, such that the signal become decoherent. In amplitude selfcal, it is also possible to loss structures, because the inperfect clean model. It is not so trivial to clean the diffuse extended structures well enough for a self-calibration, given your present uv-coverage and S/N.

**Comment by keflavich** [comment]
Yes, but I believe that my high S/N cut should automatically exclude any solutions in fields with no signal.  I will check this.

The problem, though, is that it is precisely the fields with high S/N that have simply disappeared.  I don't know what this disappearance means - they are not flagged out, so why are they gone?

**Comment by baobabyoo** [comment]
Disappear means something like the box in the bottom left? This is likely a bug. I had a ticket 2 years ago. It got a low priority since we know how to live with it. You can try using a slightly bigger imsize, and make a polygonal clean box that nicely follow the edge of your mosaic field of view.

**Comment by baobabyoo** [comment]
In this test, you can first set niter=0 to see if you can recover all field, without wasting time to the wrong clean.

**Comment by keflavich** [comment]
The imsize is already huge compared to the image:
image
I am fairly sure this has nothing to do with cleaning since entire pointings have disappeared, but I will confirm this by creating a dirty map.  Yes, OK, this is exactly what you said (niter=0), but my purpose is to confirm whether or not clean is the issue.

On a different thread, there is something funny going on with my amp cal.  This shows amplitude vs time, and note that most of the amplitudes are 0.5.   I think they should be 1....
image

**Comment by baobabyoo** [comment]
Hmm, the amplitude solution is bad. Normally amplitude varies at a much larger timescale than phase. It is adequate to start with a solution interval of ~10 min. This will avoid some defect. 

Not sure what happens to the disappearing field, a new bug? Can you recover by just imaging one of them?

**Comment by keflavich** [comment]
I can confirm, the lost fields are also lost when dirty mapping.  So clean has nothing to do with this (unless it is reading the wrong flag table...)

**Comment by keflavich** [comment]
Checking whether imaging a single field works now.  I doubt it will.

I figured out one thing, though: my S/N > 5 cut isn't enough.  I need to be field-specific too.  So I'll do that.  (i.e., there were some phase/amp solutions for fields where I didn't want them)

**Comment by baobabyoo** [comment]
Can you check the header and see if the RA and DEC of those fields are revised?
I had a few case like 350 deg is revised to -10 deg. Then clean doesn't know how to place it back to the field.

**Comment by baobabyoo** [comment]
Yes you can derive phase solution independently for groups of field, using the append='T' option. This will give you some flexibility.

**Comment by keflavich** [comment]
Why do I need to use `append='T'`?  I was going to just do:

```
gaincal(vis=vis0, caltable="phase.cal", field=",".join(fields_after_split), solint='inf',
        calmode="p", refant="", gaintype="G", minsnr=5)
```

I'm not sure how to check the RA/Dec of individual fields in UV space... any ideas?

**Comment by keflavich** [comment]
if I try to image just one field that has 'disappeared', I get:

```
2015-12-11 08:19:52     WARN    SkyEquation::makeMosaicPSF      Mosaic psf is off.
2015-12-11 08:19:52     WARN    SkyEquation::makeMosaicPSF+     Could be no pointing in center of image
2015-12-11 08:19:52     WARN    SkyEquation::makeMosaicPSF+     Will retry to make an approximate one without primary beam
```

so perhaps it is the RA/Dec issue....

**Comment by keflavich** [comment]
hmm, actually no.  If I dirty-image just one of those fields, it works.

**Comment by baobabyoo** [comment]
For a single field, imaging RA=-10 deg can work. But clean doesn't know how to image together RA=-10 deg and RA=350 deg. I was reading this from .fits file. But I guess "browsetable()" will work.

**Comment by keflavich** [comment]
I'm not sure how to interpret UV data in terms of RA, Dec when browsing a table.

**Comment by keflavich** [comment]
OK, so here's the minimal reproduction of the issue:

image

```
# Extras to try to reproduce bug:
phasecenter = "J2000 19:23:41.629000 +14.30.42.38000"
imsize = [3072,3072]
cell = '0.05arcsec'
solint = 'int'
threshold = '50.0mJy'
multiscale = [0,5,15,45]
vis4 = 'w51_contvis_selfcal_4.ms'
myimagebase = "selfcal_spw3_selfcal_4ampphase_mfs_dirty"
os.system('rm -rf {0}.*'.format(myimagebase))

# right image:
clean(vis=vis4, imagename=myimagebase,
      field="", spw='', mode='mfs', outframe='LSRK',
      multiscale=multiscale,
      interpolation='linear', imagermode='mosaic', interactive=False,
      minpb=0.4,
      niter=0, threshold='5mJy', imsize=imsize, cell=cell,
      phasecenter=phasecenter, weighting='briggs',
      usescratch=True, pbcor=True, robust=-2.0)
exportfits(myimagebase+'.image', myimagebase+'.image.fits', dropdeg=True, overwrite=True)
impbcor(imagename=myimagebase+'.image',pbimage=myimagebase+'.flux',
        outfile=myimagebase+'.image.pbcor', overwrite=True)
exportfits(myimagebase+'.image.pbcor', myimagebase+'.image.pbcor.fits', dropdeg=True, overwrite=True)
exportfits(myimagebase+'.model', myimagebase+'.model.fits', dropdeg=True, overwrite=True)
exportfits(myimagebase+'.residual', myimagebase+'.residual.fits', dropdeg=True, overwrite=True)


# left image:
myimagebase = "selfcal_spw3_selfcal_4ampphase_mfs_dirty_field32"
os.system('rm -rf {0}.*'.format(myimagebase))
clean(vis=vis4, imagename=myimagebase,
      field="28", spw='', mode='mfs', outframe='LSRK',
      multiscale=multiscale,
      interpolation='linear', imagermode='mosaic', interactive=False,
      minpb=0.4,
      niter=0, threshold='5mJy', imsize=imsize, cell=cell,
      phasecenter="", weighting='briggs',
      usescratch=True, pbcor=True, robust=-2.0)
exportfits(myimagebase+'.image', myimagebase+'.image.fits', dropdeg=True, overwrite=True)
impbcor(imagename=myimagebase+'.image',pbimage=myimagebase+'.flux',
        outfile=myimagebase+'.image.pbcor', overwrite=True)
exportfits(myimagebase+'.image.pbcor', myimagebase+'.image.pbcor.fits', dropdeg=True, overwrite=True)
exportfits(myimagebase+'.model', myimagebase+'.model.fits', dropdeg=True, overwrite=True)
exportfits(myimagebase+'.residual', myimagebase+'.residual.fits', dropdeg=True, overwrite=True)
```

**Comment by baobabyoo** [comment]
If RA and DEC is exactly the problem, then just revising the header will recover it. For .fits, I normally just use vim or emacs. Or uvputhd in Miriad. Not sure how to do this with CASA.

**Comment by keflavich** [comment]
Oh, no, this is not a FITS problem.  This is in the actual imaging.  The image has fine coordinates, the data are just set to NaN.

**Comment by baobabyoo** [comment]
Which data is set to NaN? Amplitude?

**Comment by keflavich** [comment]
the image data are NaN.  Nothing _appears_ to be wrong with the UV data, though I haven't investigated super thoroughly.  Look at the image: https://cloud.githubusercontent.com/assets/143715/11739219/1fa09b92-9fea-11e5-9e41-b88f4469ccb3.png.  This image was made with identical UV data, just with different field selection within clean.  In one image, which includes all fields, pointing #32 is missing completely.  In the image that _only_ includes pointing #32, it is there, and the _only_ difference between this is the change of the `field` parameter.

**Comment by baobabyoo** [comment]
This is the most likely because of the 360 deg ambiguity in RA. I think manually fix the header would work.

**Comment by keflavich** [comment]
what header, though?  the FITS header is exactly correct.

**Comment by baobabyoo** [comment]
Not sure what are those keywords in CASA. But maybe exportuvfits corrects the 360 deg ambiguity. I am thinking if you load those .fits file back to CASA again, you might again be able to image them.

**Comment by keflavich** [comment]
I still don't understand what you mean when you say "load .fits file back to CASA" or "image them".  The CASA .image files are also fine in terms of coordinates, but they are otherwise identical to the FITS images.   When you say "image them", I think you mean use CLEAN to ft the UV data into the image plane, but they are already images, so I don't understand.

**Comment by baobabyoo** [comment]
Ahh yes I was talking about visibility. I am guessing that your visibility is subject to a 360 deg ambiguity in RA.

**Comment by keflavich** [comment]
Right, that I understand.  I have no idea how to access the absolute sky location in UV space... that is encoded in the phase, but this is now something I've never fully understood in interferometry, much less in how CASA stores the data.

**Comment by baobabyoo** [comment]
It is a defined "phase referencing center" not phase. Normally it is the same with the antenna pointing center.

**Comment by keflavich** [comment]
right, and that makes perfect sense.  However, I've manually specified the phase reference center (keyword `'phasecenter'`) in both cases, and it is identical.  But... hm.... is there a phase center specified for each antenna?  There must be.  I guess this comes from the pointing tables.  But that should not be getting modified.  I'll look to see if it is... but... I don't know where CASA stores this, because splitted tables don't have pointing tables... maybe listobs will show it.

**Comment by keflavich** [comment]
according to listobs, all pointings have positive RA

**Comment by keflavich** [comment]
there is also a `FIELD` table, which has a `REFERENCE_DIR` column, which I have verified:

```
tb.open(vis4+'/FIELD')
a,b = tb.getcol('REFERENCE_DIR')
CASA <34>: a
  Out[34]:
array([[-1.20561316, -1.20584148, -1.20579323, -1.20574498, -1.20569673,
        -1.20564848, -1.20560023, -1.20555198, -1.20582382, -1.20577557,
        -1.20572732, -1.20567907, -1.20563082, -1.20558257, -1.20553432,
        -1.20548607, -1.20575791, -1.20570966, -1.20566141, -1.20556491,
        -1.20551666, -1.20546841, -1.20574025, -1.205692  , -1.20564375,
        -1.2055955 , -1.20554725, -1.205499  , -1.20545075, -1.2054025 ,
        -1.20567434, -1.20562609, -1.20557784, -1.20552959, -1.20548134,
        -1.20543309, -1.20538484]])

CASA <35>: b
  Out[35]:
array([[ 0.25327821,  0.25333743,  0.25329072,  0.25324401,  0.2531973 ,
         0.25315059,  0.25310388,  0.25305717,  0.25340124,  0.25335453,
         0.25330782,  0.25326111,  0.2532144 ,  0.25316769,  0.25312098,
         0.25307427,  0.25341833,  0.25337162,  0.25332492,  0.2532315 ,
         0.25318479,  0.25313808,  0.25348214,  0.25343543,  0.25338872,
         0.25334201,  0.2532953 ,  0.25324859,  0.25320188,  0.25315517,
         0.25349924,  0.25345253,  0.25340582,  0.25335911,  0.2533124 ,
         0.25326569,  0.25321898]])
```

**Comment by baobabyoo** [comment]
Hmm, the actual problem seems to be very obscured. I can try making a dirty image with Miriad, and see if I can recover a full mosaic.

**Comment by keflavich** [comment]
OK, I'll tar it up and send it.... will also file a helpdesk ticket

**Comment by keflavich** [comment]
https://www.dropbox.com/s/ki3rcik32k02xim/w51_contvis_selfcal_4.ms.tar.gz?dl=0

**Comment by baobabyoo** [comment]
I hit strange problem when loading things to Miriad, will ask how to avoid it:

```
hlu@pc018656$ fits in=test.fits op=uvin out=test.miriad

fits: CVS Revision 1.24, 2013/03/14 17:33:00 UTC

### Warning [fits]:  2 unrecognised cards were written to the history file
### Warning [fits]:  Ignored random parameter INTTIM
Determining various defaults ...
  Assuming systemp=40
  Assuming jyperk=40

Analysing the extension tables ...
  Using antenna table information
### Fatal Error [fits]:  Too many antennas for me
```

**Comment by baobabyoo** [comment]
screenshot from 2015-12-11 15 03 11

I exported your ms to .fits, and then load it back to CASA, and then generate the dirty image in CASA. This doesn't recover the mosaic field.

**Comment by keflavich** [comment]
right, so this really is a CASA error

**Comment by keflavich** [comment]
I've filed a ticket about this

**Comment by keflavich** [comment]
I'm merging this code into master, but we can continue the conversation here.

**Comment by baobabyoo** [comment]
The problem with Miriad is that the maximum number of antennas is 64. 
It seems like you have observations with two array configurations. So it reads like it has 73 antennas. I tried splitting the data. But it seems like the full antenna table is retained in the split CASA data. :Q

**Comment by keflavich** [comment]
Well, that's [the problem you identified above](https://github.com/keflavich/W51_ALMA_2013.1.00308.S/pull/1#issuecomment-163936278), but I don't think that problem would have caused the [imaging problem](https://cloud.githubusercontent.com/assets/10827289/11745431/54d60468-a018-11e5-99b0-61eb2e6734af.png), would it?  Yes, I have two array configs here.

**Comment by baobabyoo** [comment]
Not it wouldn't. But this also means that we are not able to make MEM imaging with Miraid.  :-(

**Comment by keflavich** [comment]
Ah, understood.  Oh well.  MEM might work in CASA

**Comment by baobabyoo** [comment]
Got the reply about the Miriad loading issue. CASA concatenates metadata (used, or not used)  including the not used antenna table, etc. This confuses other software..... 

---

Hi Baobab,

Ah, yes. part of CASA table management problems. Miriad's streaming data is so much simpler.
The data and uvvariables are simply catenated , so any metadata, including antennas, is updated.
I'm anticipating similar problems elsewhere, with more versatile observations which ALMA telescope
is capable of.

**Pull request merged**
